### ISSUE TITLE
Output feature request

### ISSUE THREAD

**Issue by ykassif** [Skarafaz/mercury#11]
Will this app be able to output the results from a command onto the log file or a separate dialog.

**Comment by Skarafaz** [comment]
This feature may be implemented in future.

**Comment by bart9h** [comment]
This would be very useful.

At least show a toast if the command returns an error (rc != 0).

**Comment by dreua** [comment]
I made a branch with that feature: https://github.com/dreua/mercury/tree/feature-output
Please note that I had to remove nohup from the commands to accomplish this, so this will break things if you rely on nohup. (It is there by default and I didn't find a way to deactivate it.)

**Comment by Skarafaz** [comment]
I'm planning a big update including this feature. A good implementation is not trivial, so just be patient :).

**Comment by kjbaker-uk** [comment]
I have pulled the code last night and I am also having a look at this, I think having the feedback going to the log is not the correct course of action. However I do like how @dreua implemented the stdout but I was unable to deploy his code as the gradle3 was giving me all sorts of issues, even tho i'm using Android Studio 3. @Skarafaz I look forward to seeing what you are planning and I will also push to a branch my attempt. 

I think having the response would also allow the app to get status information from a Pi (or any other linux box) to get WiFi info, bluetooth status etc....

I think having an app with json config files to implement the functionality of the device is awesome and the best idea of this I have seen. @Skarafaz well done mate!!!

**Comment by dreua** [comment]
@D4rkC00d3r : I'm sorry that you had issues with my latest commits on the branch, they have been pushed in error. I believe my plan was to continue developing and adjusting everything for Gradle 3 but that never happened. Please try to checkout the commit 9974bfe58d2029f401c94128f4263ba7fafc2775 , that should work and I believe that is the version currently running on my device.

**Comment by Skarafaz** [comment]
@D4rkC00d3r Thanks!!

**Comment by kjbaker-uk** [comment]
@dreua Hey mate, thanks for the message I was able to see your commit earlier today but now I cant?? If I click your link in the message I can see the changes but in GitKracken I cant see your stuff at all now??

**Comment by dreua** [comment]
@D4rkC00d3r : I'm sorry I don't know GitKracken, maybe you got in "Detached head" state by checking out the commit and your Kracken is confused by that. I would try checking out the branch (`git checkout feature-output`) or pulling the branch to fix this. I just reverted the last two commits so you can just use the latest version of my feature-output branch. Good Luck!
