### ISSUE TITLE
Don't storre the Password !!!

### ISSUE THREAD

**Issue by theScrabi** [Skarafaz/mercury#12]
I like your app, but do we really have to sotore the password plain text on a smart phone? Could you make it possible for the user to just enter the password every time he wants to send a command, and if the password was not set in the config.

mfg schabi

**Comment by tnshibu** [comment]
That would be good.
If the password is stored in the JSON file, use it.
Else popup a password dialog.

**Comment by djmattyg007** [comment]
Ideally support for RSA keys would be available.
