### ISSUE TITLE
Connection through http proxy

### ISSUE THREAD

**Issue by renatocan** [Skarafaz/mercury#19]
With support for a connection using an HTTP proxy, it would be possible to send commands to SSH servers exposed using Pagekite (https://pagekite.net/), which is an awesome way of exposing an RPi Server at home since Pagekite avoids the need to configure a port forwarding on the router.

I think it is fairly easy to implement, since JSch already supports SSH connection through an http proxy (example at http://www.jcraft.com/jsch/examples/ViaHTTP.java.html).

Thanks!

[],

Renato.

**Comment by Skarafaz** [comment]
I think this feature will be included in the next release.
