### ISSUE TITLE
Icon/Skinning

### ISSUE THREAD

**Issue by rigid** [Skarafaz/mercury#2]
It would be nice if commands could have icons (maybe even dynamic ones, depending of the return value of the remote command, to signal state).

Awesome would be some kind of image-map with sensitive rectangles for each command. (so you could have an image of a remote control with commands mapped to buttons, for example)

and of course: GIF animations ;)

**Comment by Skarafaz** [comment]
The first idea (or something similar) will be probably implementend with return status and output handling.
The second one is a bit useless imho :-)

**Comment by rigid** [comment]
Great!

imho the 2nd one would improve usability when LOTS of commands are configured. Compare e.g. a 9x9 field of small rectangular icon-buttons vs. a list with 81 entries.
