### ISSUE TITLE
port forward ?

### ISSUE THREAD

**Issue by abate** [Skarafaz/mercury#20]
it would be nice to establish a port forward of a service of the remote host locally.
My use case it to access the web interface of my nas that runs on localhost:8081
in the browser on my tablet.

something like I'd do one the command line as
ssh -L 8081:127.0.0.1:8081 -L 8080:127.0.0.1:8080 192.168.1.10

**Comment by Skarafaz** [comment]
Mercury is designed to send simple commands to a server, so establishing port forwards is beyond the scope of this application.
