### ISSUE TITLE
Feature request: make individual scripts available as activities

### ISSUE THREAD

**Issue by RobbH** [Skarafaz/mercury#22]
Sorry, I am not an Android developer, just a tinkerer, so I do not know the correct vocabulary for what I'm requesting. It would be great if I could call an individual script from within Tasker. I can do this with RFO Basic, for instance. All I can do with Mercury is launch the app.

Thanks for considering this. Not being a developer, I am clueless about how difficult it would be, or what the downsides might be. I'll certainly continue using Mercury-SSH either way. I'll use it even more if I can automate some of its scripts. This is a feature I'd be willing to pay for.

**Comment by Skarafaz** [comment]
Unfortunately implementing this feature is not straightforward, but I've some ideas to test.... stay tuned!
