### ISSUE TITLE
rsync help

### ISSUE THREAD

**Issue by plegrand1** [Skarafaz/mercury#24]
i need a little help to use mercury to backup a directory from my mobile to a debian desktop.
What would be the command line ?
something like that 
/usr/bin/rsync -av -e ssh /my-mobile user@$desktop-debian:backup 
or
rsync -a --delete /src/ /dst/
but in this case the rsync command is from my desktop?
src : smartphone ?
dst : desktop

Thanks for your help

**Comment by Skarafaz** [comment]
The command is executed on the remote server, so you can run a command like this:

`rsync -ave ssh USER@MOBILE:PATH/TO/SRC /PATH/TO/DST`

to pull the target directory from the mobile device to the server... BUT you need an ssh server running on the device!
