### ISSUE TITLE
[feature-request] Homescreen widgets

### ISSUE THREAD

**Issue by 7usr7local** [Skarafaz/mercury#25]
Hi @Skarafaz,
thank you for this usefull app!

I have an idea I consider a usefull continuation of the develpment: It would be nice to have the abillity to create widgets, one per configured actions so e.g. you could tap on the widget on your phones homescreean instead of opening the app, select the computers tab and tap on the line of the command you wish to trigger.

Just an idea ... thanks for reading 😄 
Peter

**Comment by Skarafaz** [comment]
It's a good idea, but the structure of this app makes it quite hard to implement.
