### ISSUE TITLE
Dynamic Variables

### ISSUE THREAD

**Issue by skluthe** [Skarafaz/mercury#29]
Please consider implementing the ability to add a variable into commands that allow user input. For example:

I have a server with nmap to do some pentesting from outside of my local network. I would like to be able to push the button to run the command and get a prompt that allows me to input the IP I would like to scan. 

If you need some help, let me know. I haven't done much development but will dedicate some time to help this happen with some direction. 

Thanks!

**Comment by skluthe** [comment]
For an example of this take a look at rundeck (it's where I got the idea from)

**Comment by Skarafaz** [comment]
Hi! I'm sorry for the late reply.

Of course I will consider this for future release.
