### ISSUE TITLE
command arguments

### ISSUE THREAD

**Issue by rigid** [Skarafaz/mercury#3]
commands should have optional arguments.
Mercury would then request input from the user after command selection and before sending it.
Most important would be string arguments, but since the android UI offers a rich set of input methods, also number inputs, date/time, sliders, list selections etc. could be implemented as needed.

**Comment by Skarafaz** [comment]
Mercury is intended to send preconfigured commands with just a tap, so providing arguments for each execution goes against the app's philosophy.
