### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by hoasis2** [Skarafaz/mercury#30]
Thanks for this valuable app!

I installed it on my (Sony Bravia) Android TV and it works great with a hardware keyboard or mouse. With the remote control of the TV, however, I can select a command, but unfortunately I can't execute it.

Any idea why this happens?

**Comment by hoasis2** [comment]
I've now found out why it's not working always.
Is there a chance to fix this?

A command can only be executed by tapping on a touchscreen, but not by pressing Enter on a keyboard or OK button on the TV remote control.

**Comment by Skarafaz** [comment]
Hi! This app has never been tested on a TV, thanks for doing that :)
I will release a fix asap.

**Comment by ZacharyFoxx** [comment]
Hello,

One more supporting this request. I have an OUYA that I use with sharing via NFS on a router with openwrt. If you have d-pad support to access the menus and commands it would be great.

Finally, would it be possible to have an option to fix the direction of rotation of the screen between landscape or portrait? I tested the application in OUYA and the standard screen is in portrait and when I access the LOG and SETTINGS options the screen is in landscape, ideal for TV.

**Comment by hoasis2** [comment]
> Finally, would it be possible to have an option to fix the direction of rotation of the screen between landscape or portrait? I tested the application in OUYA and the standard screen is in portrait and when I access the LOG and SETTINGS options the screen is in landscape, ideal for TV.

Can't you use the [set-orientation](https://www.apkmirror.com/apk/eyes-free-project/set-orientation/set-orientation-1-1-4-release/set-orientation-1-1-4-android-apk-download/) app?
