### ISSUE TITLE
Reading position in Help page gets lost after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [Skarafaz/mercury#32]
The reading position of Help page restores after device rotation, I have to manually scroll to the position I read before.

![Screen Shot 2020-08-09 at 8 45 03 PM](https://user-images.githubusercontent.com/67744580/89732421-81b54b80-da81-11ea-9f4b-464a7ac6d553.png)
![Screen Shot 2020-08-09 at 8 45 10 PM](https://user-images.githubusercontent.com/67744580/89732422-837f0f00-da81-11ea-810c-83a876df9f7c.png)

**Comment by Skarafaz** [comment]
I'll take a look, but I don't think this is a real issue ;)
