### ISSUE TITLE
Using custom and/or separate keys for separate connections.

### ISSUE THREAD

**Issue by samuelrajan747** [Skarafaz/mercury#34]
I love this app. Please add the ability to 
  1) use separate SSH keys for separate connections. 
  2) make the app generate multiple SSH keys
  3) provide keys that are generated elsewhere ( not by this app )
Thanks in advance

**Comment by Skarafaz** [comment]
Yes, this is planned.

**Comment by cnbeam** [comment]
Hi Skarafaz,

i like the simple mercury ssh client very much but it seems you are not working anymore on this project or can we expect new features like support for up to date ssh key algorithms? ssh-rsa doesn't seem trustworthy anymore. At least on my ssh servers.
