### ISSUE TITLE
[Feature request] OpenKeychain integration

### ISSUE THREAD

**Issue by rEnr3n** [Skarafaz/mercury#38]
I use [Password Store](https://github.com/android-password-store/Android-Password-Store) on my phone and I use [OpenKeychain](https://www.openkeychain.org/) alongside it for storing the keys. Please add support for OpenKeychain as I don't want to maintain another set of keys.

**Comment by TheOPtimal** [comment]
I second this, however how would you define which key to access in the configuration files?
