### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by renatocan** [Skarafaz/mercury#6]
I noticed a problem when I used a password with the character "#". To make it work, I had to change the server's password. Moreover, I could not make commands such as "/etc/init.d/something" work. I didn't go any further, but, as the commands worked when executed directly om a SSH shell, I suspect the character "/" is causing some problems too. Is there a way to use these characters on the config file ?

Thanks!

Renato.

**Comment by Skarafaz** [comment]
Thank you for pointing that out. I will take a look at it!

**Comment by Skarafaz** [comment]
I cannot reproduce this bug, both login with password containing "#" and "/etc/init.d" commands work.

**Comment by renatocan** [comment]
I tested it again and I noticed the problem with the password happens only when the "#" is the first character of the password. I am using version 1.0.0, obtained from F-Droid. About the "/etc/init.d" commands, I'll test it again and tell you later. Thanks!

[]

Renato.

**Comment by zeyios** [comment]
I use the cmd like "/etc/test.sh", it doesn't work. but the toast say "Command send".. I am using version 1.0.1

**Comment by Skarafaz** [comment]
I don't think the problem is related to the command syntax (I successfully sent a lot of similar commands to my servers), Maybe the connection strategy used by the app cuts the execution of some commands. I'm working to solve this issue

**Comment by Skarafaz** [comment]
Maybe this commit eef49740cd37dcb4b7346b0a29bd23f3b6e22ee1 could have solved the problem with the execution of some commands (e.g. /etc/init.d/something).
