### ISSUE TITLE
persistent connection

### ISSUE THREAD

**Issue by Arnaudv6** [Skarafaz/mercury#7]
_Hello Skarafaz and thanks for this awesome soft.
I mainly use it to send keys with xdotools.
So the connection/deconnection time lessens my experience, and I should like to see an option added for persistent connections in conf files.
Moreover, each of my commands start with_
export DISPLAY=':0.0'
_The ability to run commands when starting (or stopping) a session would be soooo appreciated.
Arnaudv6_

**Comment by stephanritscher** [comment]
Hi Arnaudv6,

I think #14 is along the lines you think. It provides the persistent connection (though separate exec channels are used) as you suggested.

You can workaround the lack of commands run at the start of the session by inserting the code into .bashrc (or similar). If the commands should only run for MercurySSH, either you use a separate user or you check the variable SSH_CONNECTION which contains the ip and port of both endpoints.

All the best
Stephan

**Comment by Arnaudv6** [comment]
Thanks Stephan : I am gessing this will do indeed.
I can't test right now, but I close the bug.
Thanks also for your advice.
All the best
Arnaud
